import { Injectable, inject } from '@angular/core';
import fhir, {QuestionnaireItem} from "fhir/r4";
import jsonTraverse from 'traverse';
import { Util } from '../lib/util';
import { FormService } from './form.service';
import {ExtensionsService} from "./extensions.service";
import {
  ANSWER_OPTION_METHOD_ANSWER_OPTION, ANSWER_OPTION_METHOD_SNOMED_VALUE_SET, ANSWER_OPTION_METHOD_VALUE_SET,
  EXTENSION_URL_ANSWER_EXPRESSION, EXTENSION_URL_CALCULATED_EXPRESSION,
  EXTENSION_URL_ENABLEWHEN_EXPRESSION, EXTENSION_URL_ENTRY_FORMAT,
  EXTENSION_URL_INITIAL_EXPRESSION, EXTENSION_URL_QUESTIONNAIRE_UNIT,
  EXTENSION_URL_QUESTIONNAIRE_UNIT_OPTION, EXTENSION_URL_VARIABLE
} from "../lib/constants/constants";
// import {TerminologyServerComponent} from "../lib/widgets/terminology-server/terminology-server.component";
import {AnswerValueSetComponent} from "../lib/widgets/answer-value-set/answer-value-set.component";

@Injectable({
  providedIn: 'root',
})
export class ImportQuestionnaireService {
  extensionService = inject(ExtensionsService);

  constructor() { }

  /**
   * Update imported questionnaire with custom fields.
   *
   * The schema of custom fields are defined in the schema files, these fields are internal and are meant to
   * help with UI logic. They will not be present when imported from external sources. The values of the fields are
   * based on the other questionnaire fields.
   *
   * @param questionnaire - Imported questionnaire.
   * @param formService - Injecting the service during the constructor will result in circular dependency issues, so we pass it in as a parameter when needed.
   *
   * @return - Returns the updated questionnaire.
   */
  updateRawQuestionnaire(questionnaire: fhir.Questionnaire, formService: FormService): fhir.Questionnaire {
    const thisService = this;
    // Remove any meta.tag.code generated by LForms.
    this.removeConverterMetaTag(questionnaire.meta);
    jsonTraverse(questionnaire).forEach(function(x) {
      if (x?.item) {
        // Convert any help text items to __$helpText.
        thisService.parseHelpText(x);
      }
      if(x?.type === 'coding') {
        x.__$isAnswerList = true;
      }
      if(x?.answerOption) {
        x.__$isAnswerList = true;
        x.__$answerOptionMethods = ANSWER_OPTION_METHOD_ANSWER_OPTION;
        x.__$pickInitial = {
          repeats: x.repeats,
          selectedAnswers: x.answerOption.filter((ao) => {ao.initialSelected})
        }
      }
      if(x?.answerValueSet) {
        x.__$isAnswerList = true;
        const snomedUser = formService?.isSnomedUser();
        if(snomedUser && x.answerValueSet.startsWith(AnswerValueSetComponent.snomedBaseUri)) {
          x.__$answerOptionMethods = ANSWER_OPTION_METHOD_SNOMED_VALUE_SET;
        }
        else {
          x.__$answerOptionMethods = ANSWER_OPTION_METHOD_VALUE_SET;
        }
      }

      if(x?.enableWhen?.length > 0) {
        x.__$enableWhenMethod = 'enablewhen-cond';
        x.enableWhen.forEach((ew) => {
          ew.__$answerType = thisService.getItemType(questionnaire, ew.question);
        });
      }
      if(x?.extension && x.extension.length > 0) {
        thisService.updateExtensions(x.extension);
        thisService.updateExtensionRelatedCustomFields(x);
      }
    });

    return questionnaire;
  }

  /**
   * Update some custom fields based on extensions. Makes a copy to avoid changing the original.
   *
   * @param extParent - Typically a questionnaire's item which contains extensions. The function will update the custom
   *   fields, on this object based on the extensions it contains.
   */
  updateExtensionRelatedCustomFields(extParent: {extension: fhir.Extension[], [key: string]: any}) {
    // Terminology server.
    for (let i = 0; i < extParent.extension.length; i++) {

      const extension = JSON.parse(JSON.stringify(extParent.extension[i]));
      switch (extension.url) {
        // TODO -
        // Terminology server should follow the same logic, but for now
        // leaving it as is until the changes are sorted out.
        /*
        case TerminologyServerComponent.PREFERRED_TERMINOLOGY_SERVER_URI:
          extParent.__$terminologyServer = extension.valueUrl || '';
          break;
        */
        case EXTENSION_URL_VARIABLE:
          if(!extParent.__$variable) {
            extParent.__$variable = [];
          }
          extParent.__$variable.push(extension);
          break;

        case EXTENSION_URL_INITIAL_EXPRESSION:
          extParent.__$valueMethod = 'compute-initial';
          extParent.__$initialCalculatedExpression = extension;
          break;

        case EXTENSION_URL_CALCULATED_EXPRESSION:
          extParent.__$valueMethod = 'compute-continuously';
          extParent.__$initialCalculatedExpression = extension;
          break;

        case EXTENSION_URL_ANSWER_EXPRESSION:
          extParent.__$isAnswerList = true;
          extParent.__$answerOptionMethods = 'answer-expression';
          extParent.__$answerExpression = extension;
          break;

        case EXTENSION_URL_ENABLEWHEN_EXPRESSION:
          extParent.__$enableWhenMethod = 'enablewhen-expression';
          extParent.__$enableWhenExpression = extension;
          break;

        case EXTENSION_URL_ENTRY_FORMAT:
          extParent.__$entryFormat = extension.valueString;
          break;

        case EXTENSION_URL_QUESTIONNAIRE_UNIT:
        case EXTENSION_URL_QUESTIONNAIRE_UNIT_OPTION:
          if(!extParent.__$units) {
            extParent.__$units = [];
          }
          extParent.__$units.push(extension);
          break;

        default:
          break;
      }
    }
  }

  /**
   * Update extension object with custom fields like __$stringify etc.
   * @param extensions - Array of extensions.
   */
  updateExtensions(extensions: fhir.Extension[]) {
    // x.extension is an array.
    extensions.forEach((ext) => {
      this.extensionService.updateExtension(ext);
    });
  }


  /**
   * Look for help extension on the child `item` and update __$helpText field.
   * @param itemObj
   */
  parseHelpText(itemObj: fhir.QuestionnaireItem) {
    let htIndex = Util.findItemIndexWithHelpText(itemObj.item);

    if(htIndex >= 0) {
      const helpText = itemObj.item[htIndex];
      jsonTraverse(itemObj).set(['__$helpText'], helpText);
      itemObj.item.splice(htIndex, 1);
      if(itemObj.item.length === 0) {
        delete itemObj.item;
      }
    }
  }

  /**
   * Remove meta tag added by questionnaire converter.
   * @param meta
   */
  removeConverterMetaTag(meta: fhir.Meta): fhir.Meta {
    if(meta?.tag) {
      meta.tag = meta.tag.filter((tag) => {
        return ! /^\s*(lformsVersion\s*:)|(lhc-qnvconv-)/i.test(tag.code);
      });
      if(meta.tag.length === 0) {
        delete meta.tag;
      }
    }
    return meta;
  }

  /**
   * Utility to get the `type` of the `item` identified by the linkId.
   * @param questionnaire - Questionnaire to search through.
   * @param linkId - Link id of the item.
   */
  getItemType(questionnaire, linkId) {
    const recurse = ((items: QuestionnaireItem []): string => {
      if(!items || !items.length) {
        return null;
      }

      let ret = null;
      for (let i = 0; i < items.length && !ret; i++) {
        const el = items[i];
        if (el.linkId === linkId) {
          ret = el.type;
        }
        else {
          ret = recurse(el.item);
        }
      }
      return ret;
    });

    return recurse(questionnaire.item);
  }
}
