import { Injectable, inject } from '@angular/core';
import fhir from "fhir/r4";
import jsonTraverse from 'traverse';
import { Util } from '../lib/util';
import { FormService } from './form.service';
import {ExtensionsService} from "./extensions.service";
import {
  EXTENSION_URL_ANSWER_EXPRESSION, EXTENSION_URL_CALCULATED_EXPRESSION,
  EXTENSION_URL_ENABLEWHEN_EXPRESSION,
  EXTENSION_URL_INITIAL_EXPRESSION, EXTENSION_URL_VARIABLE
} from "../lib/constants/constants";
import {TerminologyServerComponent} from "../lib/widgets/terminology-server/terminology-server.component";
import {ObservationLinkPeriodComponent} from "../lib/widgets/observation-link-period/observation-link-period.component";

@Injectable({
  providedIn: 'root',
})
export class ImportQuestionnaireService {
  extensionService = inject(ExtensionsService);

  constructor() { }

  /**
   * Import a questionnaire from a JSON string.
   * @param jsonString - The JSON string representing the questionnaire.
   * @returns The parsed questionnaire object.
   */
  importFromJSON(jsonString: string): fhir.Questionnaire {
    let q: fhir.Questionnaire;
    try {
      const questionnaire = JSON.parse(jsonString);
      q = this.updateRawQuestionnaire(questionnaire);
    } catch (error) {
      console.error('Failed to parse questionnaire JSON', error);
      throw error;
    }
    return q;
  }

  updateRawQuestionnaire(questionnaire: fhir.Questionnaire): fhir.Questionnaire {
    const thisService = this;
    // Remove any meta.tag.code generated by LForms.
    this.removeConverterMetaTag(questionnaire.meta);
    jsonTraverse(questionnaire).forEach(function(x) {
      if (x?.item) {
        // Convert any help text items to __$helpText.
        thisService.parseHelpText(x);
      }
      if(x?.answerOption || x?.type === 'coding' || x?.answerValueSet || x?.answerConstraint) {
        x.__$isAnswerList = true;
      }
      if(x?.enableWhen?.length > 0) {
        x.__$enableWhenMethod = 'enablewhen-cond';
      }
      if(x?.extension && x.extension.length > 0) {
        thisService.updateExtensions(x.extension);
        thisService.updateExtensionRelatedCustomFields(x);
      }
    });

    return questionnaire;
  }

  updateExtensionRelatedCustomFields(extParent: {extension: fhir.Extension[], [key: string]: any}) {
    // Terminology server.
    for (let i = 0; i < extParent.extension.length; i++) {
      const extension = JSON.parse(JSON.stringify(extParent.extension[i]));
      switch (extension.url) {
        /*
        case TerminologyServerComponent.PREFERRED_TERMINOLOGY_SERVER_URI:
          extParent.__$terminologyServer = extension.valueUrl || '';
          break;
          */
        case EXTENSION_URL_VARIABLE:
          if(!extParent.__$variable) {
            extParent.__$variable = [];
          }
          extParent.__$variable.push(extension);
          break;

        case EXTENSION_URL_INITIAL_EXPRESSION:
          extParent.__$valueMethod = 'initial-expression';
          extParent.__$initialCalculatedExpression = extension;
          break;

        case EXTENSION_URL_CALCULATED_EXPRESSION:
          extParent.__$valueMethod = 'calculated-expression';
          extParent.__$initialCalculatedExpression = extension;
          break;
/*
        case EXTENSION_URL_INITIAL_EXPRESSION:
          extParent.__$initialExpression = extension;
          break;

        case EXTENSION_URL_CALCULATED_EXPRESSION:
          extParent.__$calculatedExpression = extension;
          break;
*/
        case EXTENSION_URL_ANSWER_EXPRESSION:
          extParent.__$isAnswerList = true;
          extParent.__$answerExpression = extension;
          break;

        case EXTENSION_URL_ENABLEWHEN_EXPRESSION:
          extParent.__$enableWhenMethod = 'enablewhen-expression';
          extParent.__$enableWhenExpression = extension;
          break;

        default:
          break;
      }
    }
  }

  updateExtensions(extensions: fhir.Extension[]) {
    // x.extension is an array.
    extensions.forEach((ext) => {
      this.extensionService.updateExtension(ext);
    });
  }


  parseHelpText(itemObj: fhir.QuestionnaireItem) {
    let htIndex = Util.findItemIndexWithHelpText(itemObj.item);

    if(htIndex >= 0) {
      const helpText = itemObj.item[htIndex];
      jsonTraverse(itemObj).set(['__$helpText'], helpText);
      itemObj.item.splice(htIndex, 1);
      if(itemObj.item.length === 0) {
        delete itemObj.item;
      }
    }
  }

  removeConverterMetaTag(meta: fhir.Meta): fhir.Meta {
    if(meta?.tag) {
      meta.tag = meta.tag.filter((tag) => {
        return ! /^\s*(lformsVersion\s*:)|(lhc-qnvconv-)/i.test(tag.code);
      });
      if(meta.tag.length === 0) {
        delete meta.tag;
      }
    }
    return meta;
  }
}
